version: '3.5'

services:
    fatec-web:
        container_name: 'fatec-web'
        image: node:16
        command: ['yarn', 'start']
        build:
            context: .
            dockerfile: ./Dockerfile
        env_file:
            - .env
        ports:
            - '${LINK_FATEC_PORT}:3000'
        networks:
            - infra-estagio-network
        labels:
            - "traefik.http.routers.estagio-fatec-web.rule=Host(`fatec.estagio.com`)"
            - "traefik.http.routers.estagio-fatec-web.entrypoints=default"
            - "traefik.docker.network=infra-estagio-network"
            - "traefik.enable=true"
networks:
    infra-estagio-network:
        external: true
